name: movo
description: Movies application

publish_to: 'none'

version: 2.4.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state
  get: ^4.6.1

  # network
  json_annotation: ^4.4.0
  retrofit: ^3.0.1+1
  dio: ^4.0.0

  # storage
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  file_picker: ^4.5.0

  # helpers
  video_player: ^2.2.8
  wakelock: ^0.6.1+1
  collection: ^1.15.0
  flutter_hooks: ^0.18.2+1
  visibility_detector: ^0.2.2
  permission_handler: ^9.2.0

  # di
  get_it: ^7.1.3
  injectable: ^1.5.3

  # ui
  rive: ^0.8.1
  flutter_svg: ^1.0.3
  fl_chart: ^0.45.0

  # i18n
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3
  freezed: ^1.1.1
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
