name: movo
description: Movies application

publish_to: 'none'

version: 2.6.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state
  get: ^4.6.5

  # network
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6

  # storage
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15
  file_picker: ^4.6.1

  # helpers
  video_player: ^2.4.4
  wakelock: ^0.6.1+2
  collection: ^1.15.0
  flutter_hooks: ^0.18.4
  visibility_detector: ^0.3.3
  permission_handler: ^9.2.0
  device_info_plus: ^3.2.4

  # di
  get_it: ^7.1.3
  injectable: ^1.5.3

  # ui
  rive: ^0.8.4
  flutter_svg: ^1.1.0
  fl_chart: ^0.45.0

  # firebase
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1

  # i18n
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  freezed: ^2.0.3+1
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
