name: movo
description: Movies application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state
  flutter_bloc: ^7.0.0

  # network
  json_annotation: ^4.0.1
  retrofit: ^2.0.0
  dio: ^4.0.0

  # storage
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6

  # helpers
  video_player: ^2.1.6
  wakelock: ^0.5.2
  permission_handler: ^8.1.1
  flutter_downloader: ^1.6.1
  collection: ^1.15.0

  # di
  get_it: ^7.1.3
  injectable: ^1.4.1

  # ui
  rive: ^0.7.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  injectable_generator: ^1.4.1
  freezed: ^0.14.2
  lint: ^1.5.3
  hive_generator: ^1.1.0
  retrofit_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
