name: movo
description: Movies application

publish_to: 'none'

version: 2.3.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state
  get: ^4.3.8

  # network
  json_annotation: ^4.0.1
  retrofit: ^2.0.0
  dio: ^4.0.0

  # storage
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6

  # helpers
  video_player: ^2.2.5
  wakelock: ^0.5.2
  collection: ^1.15.0
  flutter_hooks: ^0.18.0
  visibility_detector: ^0.2.0

  # di
  get_it: ^7.1.3
  injectable: ^1.4.1

  # ui
  rive: ^0.7.21
  flutter_svg: ^0.22.0
  fl_chart: ^0.40.0

  # i18n
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^5.0.0
  injectable_generator: ^1.4.1
  freezed: ^0.14.5
  lint: ^1.5.3
  retrofit_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
