name: movo
description: Movies application

publish_to: 'none'

version: 2.7.8

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state
  get: ^4.6.5

  # network
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  dio: ^5.1.1

  # storage
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15
  file_picker: ^4.6.1

  # helpers
  video_player: ^2.4.4
  wakelock: ^0.6.1+2
  collection: ^1.15.0
  flutter_hooks: ^0.18.4
  visibility_detector: ^0.3.3
  permission_handler: ^9.2.0
  device_info_plus: ^3.2.4

  # di
  get_it: ^7.2.0
  injectable: ^2.1.1

  # ui
  rive: ^0.8.4
  flutter_svg: ^1.1.0
  fl_chart: ^0.45.0

  # firebase
  cloud_firestore: ^4.5.1
  firebase_core: ^2.9.0

  # i18n
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5
  freezed: ^2.3.2
  lint: ^1.8.2
  retrofit_generator: ^6.0.0+1
  logger: ^1.3.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo_filled.png'
  image_path_android: 'assets/logo.png'
  min_sdk_android: 19

  remove_alpha_ios: true
  adaptive_icon_background: '#ffffffff'
