import '../enums/movie_genre.dart';

class MovieGenreHelper {
  MovieGenreHelper._();

  static MovieGenre? fromSchema(String genre) {
    return <String, MovieGenre>{
      'Sci-Fi': MovieGenre.sciFi,
      'Comedy': MovieGenre.comedy,
      'Family': MovieGenre.family,
      'Adventure': MovieGenre.adventure,
      'Drama': MovieGenre.drama,
      'Thriller': MovieGenre.thriller,
      'Mystery': MovieGenre.mystery,
      'TV Series': MovieGenre.tvSeries,
      'Animation': MovieGenre.animation,
      'Action': MovieGenre.action,
      'Fantasy': MovieGenre.fantasy,
      'Romance': MovieGenre.romance,
      'Horror': MovieGenre.horror,
      'Crime': MovieGenre.crime,
      'Reality-TV': MovieGenre.realityTV,
      'Documentary': MovieGenre.documentary,
      'Sport': MovieGenre.sport,
      'Short': MovieGenre.short,
      'Anime': MovieGenre.anime,
      'History': MovieGenre.history,
      'Musical': MovieGenre.musical,
      'Western': MovieGenre.western,
      'Biography': MovieGenre.biography,
      'Music': MovieGenre.music,
      'War': MovieGenre.war,
      'Adult': MovieGenre.adult,
      'Auto': MovieGenre.auto,
    }[genre];
  }

// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 261, primaryName: ზღაპრული (ფენტეზი), secondaryName: Fantasy, tertiaryName: Фэнтези, backgroundImage: }, GenresDataSchema{id: 263, primaryName: საოჯახო, secondaryName: Family, tertiaryName: Семейный, backgroundImage: https://static.adjaranet.com/genres/263-5da71872982d2.jpg}, GenresDataSchema{id: 265, primaryName: ანიმაციური, secondaryName: Animation, tertiaryName: Анимация, backgroundImage: https://static.adjaranet.com/genres/265-5e8b303691e38.jpg}, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 257, primaryName: ფანტასტიკა, secondaryName: Sci-Fi, tertiaryName: Фантастика, backgroundImage: https://static.adjaranet.com/genres/257-5da71853c4076.jpg}, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 261, primaryName: ზღაპრული (ფენტეზი), secondaryName: Fantasy, tertiaryName: Фэнтези, backgroundImage: }, GenresDataSchema{id: 265, primaryName: ანიმაციური, secondaryName: Animation, tertiaryName: Анимация, backgroundImage: https://static.adjaranet.com/genres/265-5e8b303691e38.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 265, primaryName: ანიმაციური, secondaryName: Animation, tertiaryName: Анимация, backgroundImage: https://static.adjaranet.com/genres/265-5e8b303691e38.jpg}, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}, GenresDataSchema{id: 268, primaryName: მიუზიკლი, secondaryName: Musical, tertiaryName: Мюзикл, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 257, primaryName: ფანტასტიკა, secondaryName: Sci-Fi, tertiaryName: Фантастика, backgroundImage: https://static.adjaranet.com/genres/257-5da71853c4076.jpg}, GenresDataSchema{id: 261, primaryName: ზღაპრული (ფენტეზი), secondaryName: Fantasy, tertiaryName: Фэнтези, backgroundImage: }, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 254, primaryName: სპორტული, secondaryName: Sport, tertiaryName: Спорт, backgroundImage: https://static.adjaranet.com/genres/254-5da718a6ecbf3.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 255, primaryName: საშინელებათა ფილმი, secondaryName: Horror, tertiaryName: Ужас, backgroundImage: https://static.adjaranet.com/genres/255-5da718915ef4d.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 260, primaryName: მელოდრამა, secondaryName: Romance, tertiaryName: Романтика, backgroundImage: https://static.adjaranet.com/genres/260-5da717a4ca054.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 260, primaryName: მელოდრამა, secondaryName: Romance, tertiaryName: Романтика, backgroundImage: https://static.adjaranet.com/genres/260-5da717a4ca054.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 248, primaryName: მძაფრ-სიუჟეტიანი, secondaryName: Action, tertiaryName: Боевик, backgroundImage: https://static.adjaranet.com/genres/248-5da7181803087.jpg}, GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }, GenresDataSchema{id: 255, primaryName: საშინელებათა ფილმი, secondaryName: Horror, tertiaryName: Ужас, backgroundImage: https://static.adjaranet.com/genres/255-5da718915ef4d.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 263, primaryName: საოჯახო, secondaryName: Family, tertiaryName: Семейный, backgroundImage: https://static.adjaranet.com/genres/263-5da71872982d2.jpg}, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 272, primaryName: Reality-TV, secondaryName: Reality-TV, tertiaryName: Реалити-шоу, backgroundImage: }, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 255, primaryName: საშინელებათა ფილმი, secondaryName: Horror, tertiaryName: Ужас, backgroundImage: https://static.adjaranet.com/genres/255-5da718915ef4d.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }, GenresDataSchema{id: 256, primaryName: მისტიკა, secondaryName: Mystery, tertiaryName: Мистика, backgroundImage: }, GenresDataSchema{id: 259, primaryName: დეტექტივი, secondaryName: Crime, tertiaryName: Криминал, backgroundImage: https://static.adjaranet.com/genres/259-5da717570d695.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 266, primaryName: სათავგადასავლო, secondaryName: Adventure, tertiaryName: Приключения, backgroundImage: https://static.adjaranet.com/genres/266-5da718309d451.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 263, primaryName: საოჯახო, secondaryName: Family, tertiaryName: Семейный, backgroundImage: https://static.adjaranet.com/genres/263-5da71872982d2.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 272, primaryName: Reality-TV, secondaryName: Reality-TV, tertiaryName: Реалити-шоу, backgroundImage: }, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 259, primaryName: დეტექტივი, secondaryName: Crime, tertiaryName: Криминал, backgroundImage: https://static.adjaranet.com/genres/259-5da717570d695.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 257, primaryName: ფანტასტიკა, secondaryName: Sci-Fi, tertiaryName: Фантастика, backgroundImage: https://static.adjaranet.com/genres/257-5da71853c4076.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 268, primaryName: მიუზიკლი, secondaryName: Musical, tertiaryName: Мюзикл, backgroundImage: }, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 272, primaryName: Reality-TV, secondaryName: Reality-TV, tertiaryName: Реалити-шоу, backgroundImage: }, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }, GenresDataSchema{id: 319, primaryName: TV Special, secondaryName: TV Special, tertiaryName: TV Special, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}, GenresDataSchema{id: 275, primaryName: სერიალი, secondaryName: TV Series, tertiaryName: Сериал, backgroundImage: }]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 258, primaryName: კომედია, secondaryName: Comedy, tertiaryName: Комедия, backgroundImage: https://static.adjaranet.com/genres/258-5da71db53631b.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }, GenresDataSchema{id: 256, primaryName: მისტიკა, secondaryName: Mystery, tertiaryName: Мистика, backgroundImage: }, GenresDataSchema{id: 259, primaryName: დეტექტივი, secondaryName: Crime, tertiaryName: Криминал, backgroundImage: https://static.adjaranet.com/genres/259-5da717570d695.jpg}]}
// [log] MovieData.fromSchema: schema.genres = GenresSchema{data: [GenresDataSchema{id: 249, primaryName: დრამა, secondaryName: Drama, tertiaryName: Драма, backgroundImage: }, GenresDataSchema{id: 250, primaryName: თრილერი, secondaryName: Thriller, tertiaryName: Триллер, backgroundImage: }, GenresDataSchema{id: 256, primaryName: მისტიკა, secondaryName: Mystery, tertiaryName: Мистика, backgroundImage: }, GenresDataSchema{id: 259, primaryName: დეტექტივი, secondaryName: Crime, tertiaryName: Криминал, backgroundImage: https://static.adjaranet.com/genres/259-5da717570d695.jpg}]}
}
